# Generated by Django 5.2.11 on 2026-08-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airspace", "0001_initial"),
        ("drones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waiverplanning",
            name="aircraft",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="waiver_planning_entries", to="drones.drone"),
        ),
    ]
