# Generated by Django 5.2.11 on 2026-08-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0011_operation_map_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsplanning',
            name='flight_tracking_service',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
