# Generated by Django 5.2.11 on 2026-08-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0013_approvalapplication_description_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsplanning',
            name='additional_operational_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operationsplanning',
            name='crowd_mitigation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operationsplanning',
            name='operational_boundary_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operationsplanning',
            name='operations_over_people',
            field=models.CharField(blank=True, choices=[('avoided', 'Avoided'), ('part_107_compliant', 'Part 107 compliant'), ('separate_relief', 'Separate relief required'), ('requires_review', 'Requires review')], max_length=30),
        ),
    ]
