# Generated by Django 5.2.11 on 2026-08-08 04:06

from django.db import migrations, models


NO_VO_RESPONSE = (
    "Upon detection of a crewed aircraft, the RPIC will descend, reposition, "
    "land, or otherwise maneuver as necessary to maintain separation and "
    "yield right of way to all crewed aircraft."
)


def set_existing_no_vo_responses(apps, schema_editor):
    OperationsPlanning = apps.get_model("airspace", "OperationsPlanning")
    OperationsPlanning.objects.filter(has_visual_observer=False).update(
        crewed_aircraft_conflict_response=NO_VO_RESPONSE
    )


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0014_operationsplanning_additional_operational_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsplanning',
            name='crewed_aircraft_conflict_response',
            field=models.TextField(blank=True, default="Upon detection of a crewed aircraft, the RPIC will descend, reposition, or land as necessary while the Visual Observer continues reporting the aircraft's position and trajectory until the potential conflict is resolved. The RPIC will yield right of way to all crewed aircraft."),
        ),
        migrations.RunPython(
            set_existing_no_vo_responses,
            migrations.RunPython.noop,
        ),
    ]
