# Generated by Django 5.2.11 on 2026-08-08 23:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emaildeliverylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default=accounts.models.generate_invitation_token, editable=False, max_length=64, unique=True),
        ),
    ]
