# Generated by Django 5.2.11 on 2026-08-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pilotprofile',
            options={'ordering': ['user__last_name', 'user__first_name', 'user__email']},
        ),
    ]
