# Generated by Django 5.2.11 on 2026-08-05 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0003_pilotprofile_contact_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilotprofile',
            old_name='license_number',
            new_name='faa_certificate_number',
        ),
    ]
