# Generated by Django 5.2.11 on 2026-08-05 03:26

import django.core.validators
import pilot.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0005_pilotprofile_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilotprofile',
            name='logo',
        ),
        migrations.AddField(
            model_name='pilotprofile',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='JPG, PNG, or WebP. Maximum file size: 5 MB.', upload_to='pilot_logos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), pilot.validators.validate_logo_file_size]),
        ),
    ]
