# Generated by Django 5.2.11 on 2026-08-05 03:34

import django.core.validators
import pilot.models
import pilot.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0006_remove_pilotprofile_logo_pilotprofile_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilotprofile',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='JPG, PNG, or WebP. Maximum file size: 5 MB.', upload_to=pilot.models.pilot_logo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), pilot.validators.validate_logo_file_size]),
        ),
    ]
