# Generated by Django 5.2.11 on 2026-08-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pilot", "0007_alter_pilotprofile_company_logo"),
        ("drones", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Aircraft",
        ),
    ]
