# Generated by Django 5.2.11 on 2026-08-05

import django.core.validators
import django.db.models.deletion
import drones.models
import drones.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Drone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("manufacturer", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("nickname", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(max_length=150)),
                ("faa_registration_number", models.CharField(blank=True, max_length=100)),
                ("registration_date", models.DateField(blank=True, null=True)),
                ("registration_expiration", models.DateField(blank=True, null=True)),
                ("date_purchased", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive"), ("maintenance", "Maintenance"), ("damaged", "Damaged"), ("sold", "Sold"), ("retired", "Retired")], default="active", max_length=20)),
                ("safety_features", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("faa_certificate", models.FileField(blank=True, help_text="JPG, PNG, WebP, or PDF. Maximum file size: 5 MB.", upload_to=drones.models.faa_certificate_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["jpg", "jpeg", "png", "webp", "pdf"]), drones.validators.validate_faa_certificate_size])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="drones", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["manufacturer", "model", "nickname", "id"],
            },
        ),
    ]
